{
 "title": "Spring Boot Application",
 "description": "Spring Boot Application",
 "time": { "from": "2025-08-03T08:31:39.515Z", "to": "2025-08-03T10:35:40.189Z" },
 "panels": [
  { "title": "Operational", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Uptime",
   "type": "timeseries",
   "description": "Uptime",
   "gridPos": { "h": 8, "w": 19, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "up{instance=\"spring-app:8080\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Disk Free Space",
   "type": "timeseries",
   "description": "Disk Free Space",
   "gridPos": { "h": 9, "w": 9, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "disk_free_bytes{instance=\"spring-app:8080\"}",
     "legendFormat": "{{label_name}}"
    }
   ]
  },
  {
   "title": "Executed Queued Tasks",
   "type": "timeseries",
   "description": "Executed Queued Tasks",
   "gridPos": { "h": 9, "w": 10, "x": 9, "y": 9 },
   "targets": [
    { "expr": "executor_queued_tasks", "legendFormat": "{{label_name}}" }
   ]
  }
 ]
}