management.endpoints.web.exposure.include=health,prometheus,info,liquibase
management.endpoint.health.show-details=always


spring.datasource.url=jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.jpa.hibernate.ddl-auto=validate
# Specify the default schema for Hibernate
spring.jpa.properties.hibernate.default_schema=book_catalog
spring.jpa.open-in-view=true
spring.jpa.show-sql=true

# Liquibase settings
spring.liquibase.enabled=true
spring.liquibase.change-log=classpath:/db/changelog/db.changelog-master.yaml
# Drop the database before running migrations (only for DEV environment)
spring.liquibase.default-schema=book_catalog



spring.datasource.url=jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.jpa.hibernate.ddl-auto=validate
# Specify the default schema for Hibernate
spring.jpa.properties.hibernate.default_schema=book_catalog
spring.jpa.open-in-view=true
spring.jpa.show-sql=true

# Liquibase settings
spring.liquibase.enabled=true
spring.liquibase.change-log=classpath:/db/changelog/db.changelog-master.yaml
# Drop the database before running migrations (only for DEV environment)
spring.liquibase.default-schema=book_catalog

